# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: aeb30db59afee646137f441c6c7bedd8550ad58960de2216767c1af136cd5eed52e3c081978201fb34010f77a6a17a0a5c786671e46706cf54291934c6923ece

test:
  domain_name: example.com 
  secret_key_base: dc6eb539018c8fa8effa0ab529a8d867c52899f3661ebd9800d437f6672fc1323af4c72c8c2ccd04898c5316b30a48cfc89f5c92784351e42ff68350e4469ca0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
